### PR TITLE
Task-54647: Bad display for slider news

### PR DESCRIPTION
**Pull request by wassimmhamdi**
**Problem:** When you add the slider news on another page(not snapshot page) there’s a bad display : no padding and the height is not fixed.
**Fix:** I fixed the display of slider news, so I added a margin-top of the ActivityStreamList to make a separation between the Activity and the news container and I changed the attribute height of the v-window__container witch contain the news slider from inherit to fix value

### CODE REVIEW

**Comment by ghost** [comment]
### CodeSee Review Map:
[Review these changes using an interactive CodeSee Map](https://app.codesee.io/r/reviews?pr=1342&src=https%3A%2F%2Fgithub.com%2FMeeds-io%2Fsocial)

Review [in an interactive map](https://app.codesee.io/r/reviews?pr=1342&src=https%3A%2F%2Fgithub.com%2FMeeds-io%2Fsocial)

View [more CodeSee Maps](https://app.codesee.io/r/maps?src=https%3A%2F%2Fgithub.com%2FMeeds-io%2Fsocial)

#### Legend
CodeSee Map Legend

**Review by rdenarie — CHANGES_REQUESTED** [review]
Hello. I don't understand your fix. 
Please can you update your description to explain your change ? What is the root cause ? How your fix will fix the problem ?
In addition, we speak about a problem in news slider, but we have a fix in social module. So 'im not sure of what you fix

**Comment by wassimmhamdi** [comment]
PR link related to these fix in the platform-ui module 
cc @rdenarie 
https://github.com/Meeds-io/platform-ui/pull/384

**Comment by rdenarie** [comment]
So should we close this PR ?

**Pull request closed without merging**
