### PR TITLE
fix: [People search] no results displays if field has special char - EXO-65931 - Meeds-io/meeds#1083

### PR DESCRIPTION
**Pull request by akhanfir**
Prior to this change, when create user then Connect with different user and in people directory use search filter with a term, no profile displayed, special chars in profile aren't allowing to display the good users.To fix this problem, ignored in the query of the elastic search the special char.After this change, users which has the search filter values used are displayed.

### CODE REVIEW

**Comment by ahamdi** [comment]
@akhanfir Could you resolve conflicts ?

**Review by rdenarie — CHANGES_REQUESTED** [review]
can you try to create unit tests to cover added lines ?

**Comment by exo-swf** [comment]
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

**Comment by ahamdi** [comment]
@akhanfir could you resolve the conflicts ?

**Pull request closed without merging**
