### PR TITLE
MAINT-36023: Make sure that applications names and descriptions in spaces settings are translated.

### PR DESCRIPTION
**Pull request by mdiha**
Space applications names and descriptions are not translated in the space settings menu, i made sure to internationalize (I18n) these two properties.

### CODE REVIEW

**Comment by ahamdi** [comment]
Please provide a description

**Comment by mdiha** [comment]
> Please provide a description

Description added

**Review by ahamdi — CHANGES_REQUESTED** [review]
We need to use the same Bundles for applications already defined. Each application should bring its label from its resource bundles itself and we should not put references to ecms/ chat etc ... here.

**Comment by mdiha** [comment]
> We need to use the same Bundles for applications already defined. Each application should bring its label from its resource bundles itself and we should not put references to ecms/ chat etc ... here.

Okay will add a PR for each application

**Comment by mdiha** [comment]
Added PRs:
https://github.com/exoplatform/task/pull/355
https://github.com/exoplatform/wiki/pull/270
https://github.com/exoplatform/ecms/pull/1180
https://github.com/exoplatform/agenda/pull/273

**Review by ahamdi — APPROVED** [review]

**Pull request merged**
