### PR TITLE
Task-36806 : When importing csv user file with a new line at the end,…

### PR DESCRIPTION
**Pull request by rdenarie**
… we cannot import a new file after

Before this commit, when reading the csv file, if a line is empty, we don't read a new line, so we are stuck in infinite loop, preventing the executor to start new task
This commit add a readLine instruction when the read line is empty, so that we can continue in the file and reach the end.

### CODE REVIEW

**Review by azayati — APPROVED** [review]
LGTM

**Comment by hbenali** [comment]
Another PR containing this commit https://github.com/Meeds-io/social/pull/429

**Comment by rdenarie** [comment]
No need to merge this one.
In fact, when I create the PR on branche feature/maintenance, I also prepare this PR to merge on develop. I didn't that you create  a weekly PR for all maintenance issue.
So @hbenali if you confirm that this commit is (or will be) integrated in develop via the weekly maintenance PR, we can drop this one.

**Comment by hbenali** [comment]
I understand, Maintenance team merges periodically (each week) validated tasks, OK once the discussed PR is merged, i will close this. Thanks !

**Comment by hbenali** [comment]
https://github.com/Meeds-io/social/pull/429 is merged

**Pull request closed without merging**
