### PR TITLE
MAINT-44337: fix edit short message activity when it contains a link with preview plus an attached file

### PR DESCRIPTION
**Pull request by hakermi**
**FIX** edit short message activity when it contains a link with preview plus an attached file by using adapting the `UIlinkActivtyBuilder` to use the **MESSAGE** param as it will be available when the activity contains an attached file and it's extended in the same time by the `LinkActivity` params, also updating the rest service to be able to update the **MESSAGE** param when editing the activity as the old implementation will **never** update and only updating the title.

### CODE REVIEW

**Review by ahamdi — CHANGES_REQUESTED** [review]
Please add a Unit test

**Comment by hakermi** [comment]
> Please add a Unit test

done

**Comment by ahamdi** [comment]
It seems my request was not clear, I wanted a UT for org.exoplatform.social.rest.impl.activity.ActivityRestResourcesV1.java more than the UILinkActivity.java. could you cover that class too ?

**Comment by hakermi** [comment]
> It seems my request was not clear, I wanted a UT for org.exoplatform.social.rest.impl.activity.ActivityRestResourcesV1.java more than the UILinkActivity.java. could you cover that class too ?

Okay

**Comment by hakermi** [comment]
> It seems my request was not clear, I wanted a UT for org.exoplatform.social.rest.impl.activity.ActivityRestResourcesV1.java more than the UILinkActivity.java. could you cover that class too ?

Done

**Review by ahamdi — APPROVED** [review]

**Pull request merged**
