### PR TITLE
Task-43073: Add user management navigation for delegated administrators

### PR DESCRIPTION
**Pull request by AzmiTouil**

### CODE REVIEW

**Review by azayati — DISMISSED** [review]
LGTM waiting QA validation

**Review by azayati — DISMISSED** [review]
LGTM after QA validation

**Review by rdenarie — COMMENTED** [review]
Hello,
I have few questions : 

1. We are creating a new navigation. Are we sure that all existing instance, with existing data will automatically create the new navigation/page without additionnal step/property ?
2. An administrator which is also delegated will 2 user management page. Do you ask the question to the PO to confirm that this point is ok ?

**Comment by AzmiTouil** [comment]
> Hello,
> I have few questions :
> 
> 1. We are creating a new navigation. Are we sure that all existing instance, with existing data will automatically create the new navigation/page without additionnal step/property ?
> 2. An administrator which is also delegated will 2 user management page. Do you ask the question to the PO to confirm that this point is ok ?

1.Yes
2.We have already discussed it

**Review by rdenarie — APPROVED** [review]

**Pull request merged**
