### PR TITLE
TASK-40995:External user flag is still displayed next to the user fullname

### PR DESCRIPTION
**Pull request by GouadriaHanen**
user && user.external was treated as the user.external is boolean the case was that user.external is string 
fixed by comparing user.external with string value

### CODE REVIEW

**Review by ahamdi — COMMENTED** [review]
could you do the same for the enabled property.

**Comment by GouadriaHanen** [comment]
> could you do the same for the enabled property.

enabled is already boolean!

**Comment by ahamdi** [comment]
I was not clear, sorry, I meant extracting the label calculation into a computed property

**Comment by GouadriaHanen** [comment]
> I was not clear, sorry, I meant extracting the label calculation into a computed property

done!

**Review by ahamdi — APPROVED** [review]

**Pull request merged**
